/****************************************************************
* Class Name   : WebsiteAPIController
* Company      : Fingertipplus
* Created Date : 25-11-2025
* @description : This class is used for Integration with website for Capturing the Lead into Salesforce 
* @author      : Roopesh

* Change Log:
* -----------------------------------------------------------------------------
* Ver | Author          |     Date      | Description
* -----------------------------------------------------------------------------
* 1.0 | Roopesh         | 25-11-2025    | Initial version
* -----------------------------------------------------------------------------
**************************************************************/

global without sharing class WebsiteAPIController {

}